# forms.py

from flask_wtf import FlaskForm
from wtforms import IntegerField, SubmitField
from wtforms.validators import InputRequired

class MyForm(FlaskForm):
    q1 = IntegerField('q1', validators=[InputRequired()])
    q2 = IntegerField('q2', validators=[InputRequired()])
    q3 = IntegerField('q3', validators=[InputRequired()])
    q4 = IntegerField('q4', validators=[InputRequired()])
    q5 = IntegerField('q5', validators=[InputRequired()])
    q6 = IntegerField('q6', validators=[InputRequired()])
    q7 = IntegerField('q7', validators=[InputRequired()])
    q8 = IntegerField('q8', validators=[InputRequired()])
    q9 = IntegerField('q9', validators=[InputRequired()])
    q10 = IntegerField('q10', validators=[InputRequired()])
    q11 = IntegerField('q11', validators=[InputRequired()])
    q12 = IntegerField('q12', validators=[InputRequired()])
    q13 = IntegerField('q13', validators=[InputRequired()])
    q14 = IntegerField('q14', validators=[InputRequired()])
    q15 = IntegerField('q15', validators=[InputRequired()])
    q16 = IntegerField('q16', validators=[InputRequired()])
    q17 = IntegerField('q17', validators=[InputRequired()])
    q18 = IntegerField('q18', validators=[InputRequired()])
    q19 = IntegerField('q19', validators=[InputRequired()])
    q20 = IntegerField('q20', validators=[InputRequired()])
    q21 = IntegerField('q21', validators=[InputRequired()])
    q22 = IntegerField('q22', validators=[InputRequired()])
    q23 = IntegerField('q23', validators=[InputRequired()])
    q24 = IntegerField('q24', validators=[InputRequired()])
    q25 = IntegerField('q25', validators=[InputRequired()])
    q26 = IntegerField('q26', validators=[InputRequired()])
    q27 = IntegerField('q27', validators=[InputRequired()])
    q28 = IntegerField('q28', validators=[InputRequired()])
    q29 = IntegerField('q29', validators=[InputRequired()])
    q30 = IntegerField('q30', validators=[InputRequired()])
    q31 = IntegerField('q31', validators=[InputRequired()])
    q32 = IntegerField('q32', validators=[InputRequired()])
    q33 = IntegerField('q33', validators=[InputRequired()])
    q34 = IntegerField('q34', validators=[InputRequired()])
    q35 = IntegerField('q35', validators=[InputRequired()])
    q36 = IntegerField('q36', validators=[InputRequired()])
    q37 = IntegerField('q37', validators=[InputRequired()])
    q38 = IntegerField('q38', validators=[InputRequired()])
    q39 = IntegerField('q39', validators=[InputRequired()])
    q40 = IntegerField('q40', validators=[InputRequired()])
    q41 = IntegerField('q41', validators=[InputRequired()])
    q42 = IntegerField('q42', validators=[InputRequired()])
    q43 = IntegerField('q43', validators=[InputRequired()])
    q44 = IntegerField('q44', validators=[InputRequired()])

    submit = SubmitField('Submit')
